USE [master]
GO

/****** Object:  Database [Horodateur_BD]    Script Date: 2014-11-03 12:36:55 ******/
CREATE DATABASE [Horodateur_BD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Horodateur_BD', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Horodateur_BD.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Horodateur_BD_log', FILENAME = N'c:\Program Files (x86)\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Horodateur_BD_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Horodateur_BD] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Horodateur_BD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Horodateur_BD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Horodateur_BD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Horodateur_BD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Horodateur_BD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Horodateur_BD] SET ARITHABORT OFF 
GO

ALTER DATABASE [Horodateur_BD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Horodateur_BD] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Horodateur_BD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Horodateur_BD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Horodateur_BD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Horodateur_BD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Horodateur_BD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Horodateur_BD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Horodateur_BD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Horodateur_BD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Horodateur_BD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Horodateur_BD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Horodateur_BD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Horodateur_BD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Horodateur_BD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Horodateur_BD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Horodateur_BD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Horodateur_BD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Horodateur_BD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Horodateur_BD] SET  MULTI_USER 
GO

ALTER DATABASE [Horodateur_BD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Horodateur_BD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Horodateur_BD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Horodateur_BD] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Horodateur_BD] SET  READ_WRITE 
GO

